app <- ShinyDriver$new("../../")
app$snapshotInit("level of outcome")

app$setInputs(`counter1-cat_level_name` = "CR;PR;S")
app$setInputs(`counter1-cat_level_name` = "CR;PR;a;b")
app$snapshot()
app$setInputs(`counter1-cat_level_name` = "CR;PR;")
app$snapshot()
app$setInputs(`counter1-cat_level_name` = "CR;PR")
app$snapshot()
app$setInputs(`counter1-cat_level_name` = "CR;PR;")
app$setInputs(`counter1-cat_level_name` = "CR;PR;-")
app$snapshot()
app$setInputs(`counter1-cat_level_name` = "CR;PR;")
app$setInputs(`counter1-cat_level_name` = "CR;PR;;;")
app$snapshot()
