app <- ShinyDriver$new("../../")
app$snapshotInit("con_module")

app$setInputs(`counter1-n_arms` = 8)
app$setInputs(`counter1-n_arms` = 9)
app$setInputs(`counter1-n_arms` = 8)
app$setInputs(`counter1-n_arms` = 7)
app$setInputs(`counter1-n_arms` = 1)
app$setInputs(`counter1-n_arms` = 0)
app$snapshot()
app$setInputs(`counter1-n_arms` = character(0))
app$setInputs(`counter1-n_arms` = -1)
app$snapshot()
app$setInputs(`counter1-n_arms` = 3)
app$setInputs(`counter1-n_arms` = 6)
app$snapshot()
app$setInputs(`counter1-n_arms` = character(0))
app$setInputs(`counter1-save_table` = "click")
app$snapshot()
